import java.util.HashMap;

public class cs2CaseSim {
    public static void main(String[] args) {
        HashMap < String, Double > possibleSkins = new HashMap < > ();
        possibleSkins.put("AK-47 | Nightwish", 0.0031969);
        possibleSkins.put("MP9 | Starlight Protector", 0.0031969);
        possibleSkins.put("MP7 | Abyssal Apparition", 0.010667);
        possibleSkins.put("Dual Berettas | Melondrama", 0.010667);
        possibleSkins.put("FAMAS | Rapid Eye Movement", 0.010667);
        possibleSkins.put("PP-Bizon | Space Cat", 0.031960);
        possibleSkins.put("XM1014 | Zombie Offensive", 0.031960);
        possibleSkins.put("G3SG1 | Dream Glade", 0.031960);
        possibleSkins.put("M4A1-S | Night Terror", 0.031960);
        possibleSkins.put("USP-S | Ticket to Hell", 0.031960);
        possibleSkins.put("MP5-SD | Necro Jr.", 0.11417);
        possibleSkins.put("SCAR-20 | Poultrygeist", 0.11417);
        possibleSkins.put("Sawed-Off | Spirit Board", 0.11417);
        possibleSkins.put("P2000 | Lifted Spirits", 0.11417);
        possibleSkins.put("MAC-10 | Ensnared", 0.11417);
        possibleSkins.put("MAG-7 | Foresight", 0.11417);
        possibleSkins.put("Five-SeveN | Scrawl", 0.11417);
        possibleSkins.put("Bowie Knife | Autotronic", 0.0);
        possibleSkins.put("Bowie Knife | Black Laminate", 0.0);
        possibleSkins.put("Bowie Knife | Bright Water", 0.0);
        possibleSkins.put("Bowie Knife | Freehand", 0.0);
        possibleSkins.put("Bowie Knife | Gamma Doppler (Emerald)", 0.0);
        possibleSkins.put("Bowie Knife | Gamma Doppler (Phase 1)", 0.0);
        possibleSkins.put("Bowie Knife | Gamma Doppler (Phase 2)", 0.0);
        possibleSkins.put("Bowie Knife | Gamma Doppler (Phase 3)", 0.0);
        possibleSkins.put("Bowie Knife | Gamma Doppler (Phase 4)", 0.0);
        possibleSkins.put("Bowie Knife | Lore", 0.0);
        possibleSkins.put("Butterfly Knife | Autotronic", 0.0);
        possibleSkins.put("Butterfly Knife | Black Laminate", 0.0);
        possibleSkins.put("Butterfly Knife | Bright Water", 0.0);
        possibleSkins.put("Butterfly Knife | Freehand", 0.0);
        possibleSkins.put("Butterfly Knife | Gamma Doppler (Emerald)", 0.0);
        possibleSkins.put("Butterfly Knife | Gamma Doppler (Phase 1)", 0.0);
        possibleSkins.put("Butterfly Knife | Gamma Doppler (Phase 2)", 0.0);
        possibleSkins.put("Butterfly Knife | Gamma Doppler (Phase 3)", 0.0);
        possibleSkins.put("Butterfly Knife | Gamma Doppler (Phase 4)", 0.0);
        possibleSkins.put("Butterfly Knife | Lore", 0.0);
        possibleSkins.put("Falchion Knife | Autotronic", 0.0);
        possibleSkins.put("Falchion Knife | Black Laminate", 0.0);
        possibleSkins.put("Falchion Knife | Bright Water", 0.0);
        possibleSkins.put("Falchion Knife | Freehand", 0.0);
        possibleSkins.put("Falchion Knife | Gamma Doppler (Emerald)", 0.0);
        possibleSkins.put("Falchion Knife | Gamma Doppler (Phase 1)", 0.0);
        possibleSkins.put("Falchion Knife | Gamma Doppler (Phase 2)", 0.0);
        possibleSkins.put("Falchion Knife | Gamma Doppler (Phase 3)", 0.0);
        possibleSkins.put("Falchion Knife | Gamma Doppler (Phase 4)", 0.0);
        possibleSkins.put("Falchion Knife | Lore", 0.0);
        possibleSkins.put("Huntsman Knife | Autotronic", 0.0);
        possibleSkins.put("Huntsman Knife | Black Laminate", 0.0);
        possibleSkins.put("Huntsman Knife | Bright Water", 0.0);
        possibleSkins.put("Huntsman Knife | Freehand", 0.0);
        possibleSkins.put("Huntsman Knife | Gamma Doppler (Emerald)", 0.0);
        possibleSkins.put("Huntsman Knife | Gamma Doppler (Phase 1)", 0.0);
        possibleSkins.put("Huntsman Knife | Gamma Doppler (Phase 2)", 0.0);
        possibleSkins.put("Huntsman Knife | Gamma Doppler (Phase 3)", 0.0);
        possibleSkins.put("Huntsman Knife | Gamma Doppler (Phase 4)", 0.0);
        possibleSkins.put("Huntsman Knife | Lore", 0.0);
        possibleSkins.put("Shadow Daggers | Autotronic", 0.0);
        possibleSkins.put("Shadow Daggers | Black Laminate", 0.0);
        possibleSkins.put("Shadow Daggers | Bright Water", 0.0);
        possibleSkins.put("Shadow Daggers | Freehand", 0.0);
        possibleSkins.put("Shadow Daggers | Gamma Doppler (Emerald)", 0.0);
        possibleSkins.put("Shadow Daggers | Gamma Doppler (Phase 1)", 0.0);
        possibleSkins.put("Shadow Daggers | Gamma Doppler (Phase 2)", 0.0);
        possibleSkins.put("Shadow Daggers | Gamma Doppler (Phase 3)", 0.0);
        possibleSkins.put("Shadow Daggers | Gamma Doppler (Phase 4)", 0.0);
        possibleSkins.put("Shadow Daggers | Lore", 0.0);
    }
}